fix: 1. build errors are ignored on retry 2. test data is overriden on retry

diff --git a/.github/actions/test/action.yaml b/.github/actions/test/action.yaml
--- a/.github/actions/test/action.yaml
+++ b/.github/actions/test/action.yaml
@@ -125,6 +125,8 @@ runs:
         BAZEL_REMOTE_URI: ${{ inputs.bazel_remote_uri }}
         USE_NETWORK_CACHE: ${{ inputs.use_network_cache }}
         CACHE_UPDATE: ${{ inputs.cache_update }}
+        TRUNCATE_ENABLED: ${{ inputs.truncate_enabled }}
+        SYNC_TO_S3: ${{ inputs.sync_to_s3 || 'false' }}
       run: |
         extra_params=(
           --run-all-tests
@@ -272,6 +274,70 @@ runs:
               fi
               ;;
           esac
+
+          echo "::group::s3-sync-logs"
+          if [ "$SYNC_TO_S3" = "true" ];
+          then
+            sudo -E -H -u github s3cmd sync --follow-symlinks --acl-private --no-progress --stats --no-check-md5 "$LOG_DIR/" "$S3_BUCKET_PATH/test_logs/${i}/"
+          fi
+          echo "::endgroup::"
+
+          NEED_COPYING=0
+          BUILD_FAILED=0
+          # shellcheck disable=SC2024
+          if [ -f "${JUNIT_REPORT_XML}.${i}" ];
+          then
+            set +e
+            (sudo -E -H -u github .github/scripts/tests/fail-checker.py "${JUNIT_REPORT_XML}.${i}"; echo $? > fail_checker_exit_code) |& tee fail-checker-output.log
+            set -e
+            FAIL_CHECKER_RC=$(< fail_checker_exit_code)
+            if [ "$FAIL_CHECKER_RC" -ne 0 ]; then
+              NEED_COPYING=1
+              echo "::group::Copy-failed-tests-data"
+              sudo -E -H -u github .github/scripts/tests/fail-checker.py "${JUNIT_REPORT_XML}.${i}" --paths-only | while read -r path; do
+                echo $path
+                find "${GITHUB_WORKSPACE}/${path}" -print0 | xargs -0 xargs -0 cp -L -r --parents -t "$TESTS_DATA_DIR"
+              done
+              echo "::endgroup::"
+            fi
+            if [ "$FAIL_CHECKER_RC" -eq 137 ]; then
+              BUILD_FAILED=1
+            fi
+          fi
+          if [ "$NEED_COPYING" -ne "0" ];
+          then 
+            chown -R github:github "$TESTS_DATA_DIR"
+            echo "::group::remove-binaries-from-tests-data-dir"
+            find "$TESTS_DATA_DIR" -type f -print0 | xargs -0 -n 10 file -i  | grep "application/x-executable" | awk -F: '{print $1}'
+            find "$TESTS_DATA_DIR" -type f -print0 | xargs -0 -n 10 file -i  | grep "application/x-executable" | awk -F: '{print $1}' | xargs rm
+            echo "::endgroup::"
+            echo "::group::remove-images-from-tests-data-dir"
+            find "$TESTS_DATA_DIR" -name generated_raw_image -o -name generated_vmdk_image -o -name invalid_qcow2_image -o -name qcow2_fuzzing_image -o -name NVMENBS01 -o -name generated_other_big_raw_image
+            find "$TESTS_DATA_DIR" \( -name generated_raw_image -o -name generated_vmdk_image -o -name invalid_qcow2_image -o -name qcow2_fuzzing_image -o -name NVMENBS01 -o -name generated_other_big_raw_image \) -delete
+            echo "::endgroup::"
+            echo "::group::truncate-err-files"
+            find "$TESTS_DATA_DIR" -type f -name "*.err" -size +1G -print0 | while IFS= read -r -d '' file; do
+                orig_size=$(du -h "$file" | cut -f1)
+                echo "$file - $orig_size"
+                # shellcheck disable=SC2193
+                if [ "$TRUNCATE_ENABLED" == "yes" ]; then
+                  truncate -s 1G "$file"
+                  echo "... truncated (original size was $orig_size) ..." >> "$file"
+                else
+                  echo "not truncated"
+                fi
+            done
+            echo "::endgroup::"
+            echo "::group::s3-sync-test-data"
+            if [ "$SYNC_TO_S3" = "true" ];
+            then
+              du -h "$TESTS_DATA_DIR/"
+              sudo -E -H -u github s3cmd sync --follow-symlinks --acl-private --no-progress --stats --no-check-md5 "$TESTS_DATA_DIR/" "$S3_BUCKET_PATH/test_data/${i}/"
+            fi
+            echo "::endgroup::"
+          fi
+
+
           if [ $DO_RETRY -eq 1 ]; then
             echo "Retrying..."
             echo "::endgroup::"
@@ -281,6 +347,12 @@ runs:
             break
           fi
         done
+        if [ "$BUILD_FAILED" -eq 1 ]; then
+          echo "Build failed, and is not preserved between retries so we manually exit if it was failed"
+          exit 1
+        fi
+        echo "exiting with code $FAIL_CHECKER_RC"
+        exit $FAIL_CHECKER_RC
 
     - name: copying system files
       if: ${{ !cancelled() }}
@@ -376,67 +448,6 @@ runs:
           fi
         done
 
-    - name: check test results
-      shell: bash --noprofile --norc -eo pipefail -x {0}
-      env:
-        TRUNCATE_ENABLED: ${{ inputs.truncate_enabled }}
-        SYNC_TO_S3: ${{ inputs.sync_to_s3 || 'false' }}
-      run: |
-        NEED_COPYING=0
-        # shellcheck disable=SC2024
-        for i in $(seq 1 $RETRIES); do
-          # shellcheck disable=SC2024
-          if [ -f "${JUNIT_REPORT_XML}.${i}" ];
-          then
-            set +e
-            (sudo -E -H -u github .github/scripts/tests/fail-checker.py "${JUNIT_REPORT_XML}.${i}"; echo $? > exit_code) |& tee fail-checker-output.log
-            set -e
-            RC=$(< exit_code)
-            if [ "$RC" -ne 0 ]; then
-              NEED_COPYING=1
-              echo "::group::Copy-failed-tests-data"
-              sudo -E -H -u github .github/scripts/tests/fail-checker.py "${JUNIT_REPORT_XML}.${i}" --paths-only | while read -r path; do
-                echo $path
-                find "${GITHUB_WORKSPACE}/${path}" -print0 | xargs -0 xargs -0 cp -L -r --parents -t "$TESTS_DATA_DIR"
-              done
-              echo "::endgroup::"
-            fi
-          fi
-        done
-        if [ "$NEED_COPYING" -ne "0" ];
-        then 
-          chown -R github:github "$TESTS_DATA_DIR"
-          echo "::group::remove-binaries-from-tests-data-dir"
-          find "$TESTS_DATA_DIR" -type f -print0 | xargs -0 -n 10 file -i  | grep "application/x-executable" | awk -F: '{print $1}'
-          find "$TESTS_DATA_DIR" -type f -print0 | xargs -0 -n 10 file -i  | grep "application/x-executable" | awk -F: '{print $1}' | xargs rm
-          echo "::endgroup::"
-          echo "::group::remove-images-from-tests-data-dir"
-          find "$TESTS_DATA_DIR" -name generated_raw_image -o -name generated_vmdk_image -o -name invalid_qcow2_image -o -name qcow2_fuzzing_image -o -name NVMENBS01 -o -name generated_other_big_raw_image
-          find "$TESTS_DATA_DIR" \( -name generated_raw_image -o -name generated_vmdk_image -o -name invalid_qcow2_image -o -name qcow2_fuzzing_image -o -name NVMENBS01 -o -name generated_other_big_raw_image \) -delete
-          echo "::endgroup::"
-          echo "::group::truncate-err-files"
-          find "$TESTS_DATA_DIR" -type f -name "*.err" -size +1G -print0 | while IFS= read -r -d '' file; do
-              orig_size=$(du -h "$file" | cut -f1)
-              echo "$file - $orig_size"
-              # shellcheck disable=SC2193
-              if [ "$TRUNCATE_ENABLED" == "yes" ]; then
-                truncate -s 1G "$file"
-                echo "... truncated (original size was $orig_size) ..." >> "$file"
-              else
-                echo "not truncated"
-              fi
-          done
-          echo "::endgroup::"
-          echo "::group::s3-sync"
-          if [ "$SYNC_TO_S3" = "true" ];
-          then
-            du -h "$TESTS_DATA_DIR/"
-            sudo -E -H -u github s3cmd sync --follow-symlinks --acl-private --no-progress --stats --no-check-md5 "$TESTS_DATA_DIR/" "$S3_BUCKET_PATH/test_data/"
-          fi
-          echo "::endgroup::"
-        fi
-        echo "Exiting with $RC"
-        exit $RC
 
     - name: Sync test results to S3
       if: always()
@@ -444,14 +455,6 @@ runs:
       run: |
         echo "::group::s3-sync"
         sudo -E -H -u github s3cmd sync --follow-symlinks --acl-public --no-progress --stats --no-check-md5 "$ARTIFACTS_DIR/" "$S3_BUCKET_PATH/"
-        echo "::endgroup::"
-
-    - name: Sync logs results to S3
-      if: always()
-      shell: bash --noprofile --norc -eo pipefail -x {0}
-      run: |
-        echo "::group::s3-sync"
-        sudo -E -H -u github s3cmd sync --follow-symlinks --acl-private --no-progress --stats --no-check-md5 "$LOG_DIR/" "$S3_BUCKET_PATH/test_logs/"
         echo "::endgroup::"
 
     - name: Display links to s3 summary
