Fixes for broken build

diff --git a/.github/actions/test/action.yaml b/.github/actions/test/action.yaml
--- a/.github/actions/test/action.yaml
+++ b/.github/actions/test/action.yaml
@@ -72,7 +72,6 @@ runs:
         {
           echo "TMP_DIR=$TMP_DIR"
           echo "LOG_DIR=$TMP_DIR/logs"
-          echo "YA_MAKE_OUTPUT=$TMP_DIR/logs/ya_make_output"
           echo "OUT_DIR=$TMP_DIR/out"
           echo "ARTIFACTS_DIR=$TMP_DIR/artifacts"
           echo "TESTS_DATA_DIR=$TMP_DIR/test_data"
@@ -127,6 +126,7 @@ runs:
         CACHE_UPDATE: ${{ inputs.cache_update }}
         TRUNCATE_ENABLED: ${{ inputs.truncate_enabled }}
         SYNC_TO_S3: ${{ inputs.sync_to_s3 || 'false' }}
+        GITHUB_TOKEN: ${{ github.token }}
       run: |
         extra_params=(
           --run-all-tests
@@ -211,12 +211,15 @@ runs:
         ./ya --version
         RETRIES="${NUMBER_OF_RETRIES}"
         OOM_CAN_BE_RETRIED=1
+
         echo "RETRIES=${RETRIES}" | tee -a "$GITHUB_ENV"
         RETRY_FLAG=""
         i=0
         while [ "$RETRIES" -gt 0 ]; do
           RETRIES=$((RETRIES - 1))
           i=$((i + 1))
+          RETRY_LOG_DIR="$LOG_DIR/$i"
+          sudo -E -H -u github mkdir -p "$RETRY_LOG_DIR"
           echo "::group::ya-make-test-${i}"
           set +e
           (
@@ -224,11 +227,11 @@ runs:
                 "${test_type[@]/#/--test-type=}" \
                 "${extra_params[@]}" \
                 --junit "${JUNIT_REPORT_XML}.${i}" \
-                --log-file "$LOG_DIR/ya_log.$i.txt" \
-                --evlog-file "$LOG_DIR/ya_evlog.$i.jsonl" \
+                --log-file "$RETRY_LOG_DIR/ya_log.txt" \
+                --evlog-file "$RETRY_LOG_DIR/ya_evlog.jsonl" \
                 "$RETRY_FLAG";
             echo $? > exit_code
-          ) |& tee "${YA_MAKE_OUTPUT}.${i}.txt"
+          ) |& tee "$RETRY_LOG_DIR/ya_make_output.txt"
           set -e
           RC=$(< exit_code)
           DO_RETRY=0
@@ -268,25 +271,36 @@ runs:
               # process junit with retried runs
               DO_RETRY=1
               RETRY_FLAG="-X"
-              if [ "$i" -eq "$RETRY_COUNT" ];
-              then
-                DO_RETRY=0
-              fi
               ;;
           esac
 
           echo "::group::s3-sync-logs"
           if [ "$SYNC_TO_S3" = "true" ];
           then
-            sudo -E -H -u github s3cmd sync --follow-symlinks --acl-private --no-progress --stats --no-check-md5 "$LOG_DIR/" "$S3_BUCKET_PATH/test_logs/${i}/"
+            sudo -E -H -u github s3cmd sync --follow-symlinks --acl-private --no-progress --stats --no-check-md5 "$RETRY_LOG_DIR/" "$S3_BUCKET_PATH/test_logs/${i}/"
           fi
           echo "::endgroup::"
 
           NEED_COPYING=0
-          BUILD_FAILED=0
+
           # shellcheck disable=SC2024
           if [ -f "${JUNIT_REPORT_XML}.${i}" ];
           then
+            echo "::group::muted-tests"
+            cat .github/config/muted_ya.txt
+            MUTED_CONFIG=".github/config/muted_ya.txt"
+            echo "::endgroup::"
+            echo "::group::postprocess-junit-${i}"
+            sudo -E -H -u github .github/scripts/tests/transform-ya-junit.py -i \
+              -m "${MUTED_CONFIG}" \
+              --ya-out "$OUT_DIR" \
+              --log-url-prefix "$S3_WEBSITE_PREFIX/logs/" \
+              --data-url-prefix "$S3_WEBSITE_PREFIX/test_data$GITHUB_WORKSPACE" \
+              --log-out-dir "$ARTIFACTS_DIR/logs/" \
+              "${JUNIT_REPORT_XML}.${i}"
+
+            sudo -E -H -u github .github/scripts/tests/split-junit.py -o "$JUNIT_REPORT_PARTS/${i}" "${JUNIT_REPORT_XML}.${i}"
+            echo "::endgroup::"
             set +e
             (sudo -E -H -u github .github/scripts/tests/fail-checker.py "${JUNIT_REPORT_XML}.${i}"; echo $? > fail_checker_exit_code) |& tee fail-checker-output.log
             set -e
@@ -296,12 +310,9 @@ runs:
               echo "::group::Copy-failed-tests-data"
               sudo -E -H -u github .github/scripts/tests/fail-checker.py "${JUNIT_REPORT_XML}.${i}" --paths-only | while read -r path; do
                 echo $path
-                find "${GITHUB_WORKSPACE}/${path}" -print0 | xargs -0 xargs -0 cp -L -r --parents -t "$TESTS_DATA_DIR"
+                find "${GITHUB_WORKSPACE}/${path}" -print0 | xargs -0 cp -L -r --parents -t "$TESTS_DATA_DIR"
               done
               echo "::endgroup::"
-            fi
-            if [ "$FAIL_CHECKER_RC" -eq 137 ]; then
-              BUILD_FAILED=1
             fi
           fi
           if [ "$NEED_COPYING" -ne "0" ];
@@ -336,7 +347,29 @@ runs:
             fi
             echo "::endgroup::"
           fi
+          # shellcheck disable=SC2024
+          sudo -E -H -u github gzip -c "${JUNIT_REPORT_XML}.${i}" > "$REPORTS_ARTIFACTS_DIR/orig_junit.${i}.xml.gz"
+          sudo -E -H -u github tar -C "$JUNIT_REPORT_PARTS/.." -czf "${REPORTS_ARTIFACTS_DIR}/junit_parts.${i}.xml.tar.gz" "$(basename $JUNIT_REPORT_PARTS)/${i}" "${JUNIT_REPORT_XML}.${i}"*
 
+
+          echo "::group::write-summary-${i}"
+          sudo -E -H -u github mkdir -p $ARTIFACTS_DIR/summary/${i}
+
+          cat $SUMMARY_LINKS | python3 -c 'import sys; print(" | ".join([v for _, v in sorted([l.strip().split(" ", 1) for l in sys.stdin], key=lambda a: (int(a[0]), a))]))' >> $GITHUB_STEP_SUMMARY
+
+          platform_name=$(uname | tr '[:upper:]' '[:lower:]')-$(arch)
+
+          export SUMMARY_OUT_ENV_PATH=$(mktemp -p /home/github)
+          chown github:github $SUMMARY_OUT_ENV_PATH
+          sudo -E -H -u github .github/scripts/tests/generate-summary.py \
+            --summary-out-path "$ARTIFACTS_DIR/summary/${i}/" \
+            --summary-out-env-path "$SUMMARY_OUT_ENV_PATH" \
+            --summary-url-prefix "$S3_WEBSITE_PREFIX/summary/${i}/" \
+            --build-preset "${platform_name}-${BUILD_PRESET}" \
+            "Tests" ya-test.html "${JUNIT_REPORT_XML}.${i}"
+
+          cat $SUMMARY_OUT_ENV_PATH | tee -a $GITHUB_STEP_SUMMARY
+          echo "::endgroup::"
 
           if [ $DO_RETRY -eq 1 ]; then
             echo "Retrying..."
@@ -347,12 +380,8 @@ runs:
             break
           fi
         done
-        if [ "$BUILD_FAILED" -eq 1 ]; then
-          echo "Build failed, and is not preserved between retries so we manually exit if it was failed"
-          exit 1
-        fi
         echo "exiting with code $FAIL_CHECKER_RC"
-        exit $FAIL_CHECKER_RC
+        echo "END_EXIT_CODE=${FAIL_CHECKER_RC}" |tee -a "$GITHUB_ENV"
 
     - name: copying system files
       if: ${{ !cancelled() }}
@@ -361,93 +390,25 @@ runs:
         sudo cp /var/log/kern.log "$LOG_DIR/kern.log" || true
         sudo chown -R github:github "$LOG_DIR/kern.log" || true
 
-    - name: archive unitest reports (orig)
-      shell: bash --noprofile --norc -eo pipefail -x {0}
-      run: |
-        # shellcheck disable=SC2024
-        for i in $(seq 1 $RETRIES); do
-          # shellcheck disable=SC2024
-          if [ -f "${JUNIT_REPORT_XML}.${i}" ];
-          then
-            # shellcheck disable=SC2024
-            sudo -E -H -u github gzip -c "${JUNIT_REPORT_XML}.${i}" > "$REPORTS_ARTIFACTS_DIR/orig_junit.${i}.xml.gz"
-          fi
-        done
-
-    - name: postprocess junit report
-      shell: bash --noprofile --norc -eo pipefail -x {0}
-      run: |
-        echo "::group::muted-tests"
-        cat .github/config/muted_ya.txt
-        MUTED_CONFIG=".github/config/muted_ya.txt"
-        echo "::endgroup::"
-        for i in $(seq 1 $RETRIES); do
-          if [ -f "${JUNIT_REPORT_XML}.${i}" ];
-          then
-            echo "::group::postprocess-junit-${i}"
-            sudo -E -H -u github .github/scripts/tests/transform-ya-junit.py -i \
-              -m "${MUTED_CONFIG}" \
-              --ya-out "$OUT_DIR" \
-              --log-url-prefix "$S3_WEBSITE_PREFIX/logs/" \
-              --data-url-prefix "$S3_WEBSITE_PREFIX/test_data$GITHUB_WORKSPACE" \
-              --log-out-dir "$ARTIFACTS_DIR/logs/" \
-              "${JUNIT_REPORT_XML}.${i}"
-
-            sudo -E -H -u github .github/scripts/tests/split-junit.py -o "$JUNIT_REPORT_PARTS/${i}" "${JUNIT_REPORT_XML}.${i}"
-            echo "::endgroup::"
-          fi
-        done
-
     - name: dump VM artifacts
       shell: bash --noprofile --norc -eo pipefail -x {0}
       if: ${{ !cancelled() }}
       run: |
         echo "::group::dump-vm-artifacts"
         # shellcheck disable=SC2024
-        sudo dmesg -T > "$LOG_DIR/dmesg.log" || true
-        sudo cp /var/log/atop/atop_* "$LOG_DIR/" || true
-        sudo cp /var/log/syslog "$LOG_DIR/syslog.log" || true
-        sudo chown -R github:github "$LOG_DIR/dmesg.log" "$LOG_DIR/atop_*" "$LOG_DIR/syslog.log" || true
+        sudo mkdir -p "$LOG_DIR/system_logs"
+        sudo dmesg -T > "$LOG_DIR/system_logs/dmesg.log" || true
+        sudo cp /var/log/atop/atop_* "$LOG_DIR/system_logs/" || true
+        sudo cp /var/log/syslog "$LOG_DIR/system_logs/syslog.log" || true
+        sudo chown -R github:github "$LOG_DIR/system_logs/ || true
+        sudo -E -H -u github s3cmd sync --follow-symlinks --acl-private --no-progress --stats --no-check-md5 "$LOG_DIR/system_logs/" "$S3_BUCKET_PATH/test_logs/"
         echo "::endgroup::"
 
-    - name: archive unitest reports (transformed)
+    - name: Finish with END_EXIT_CODE
       shell: bash --noprofile --norc -eo pipefail -x {0}
       run: |
-
-        sudo -E -H -u github tar -C $JUNIT_REPORT_PARTS/.. -czf $REPORTS_ARTIFACTS_DIR/junit_parts.xml.tar.gz "$(basename $JUNIT_REPORT_PARTS)" ${JUNIT_REPORT_XML}*
-
-    - name: write tests summary
-      shell: bash --noprofile --norc -eo pipefail -x {0}
-      env:
-        GITHUB_TOKEN: ${{ github.token }}
-        BUILD_PRESET: ${{ inputs.build_preset }}
-      run: |
-        # shellcheck disable=SC2024
-        for i in $(seq 1 $RETRIES); do
-          # shellcheck disable=SC2024
-          if [ -f "${JUNIT_REPORT_XML}.${i}" ];
-          then
-            echo "::group::write-summary-${i}"
-            sudo -E -H -u github mkdir -p $ARTIFACTS_DIR/summary/${i}
-
-            cat $SUMMARY_LINKS | python3 -c 'import sys; print(" | ".join([v for _, v in sorted([l.strip().split(" ", 1) for l in sys.stdin], key=lambda a: (int(a[0]), a))]))' >> $GITHUB_STEP_SUMMARY
-
-            platform_name=$(uname | tr '[:upper:]' '[:lower:]')-$(arch)
-
-            export SUMMARY_OUT_ENV_PATH=$(mktemp -p /home/github)
-            chown github:github $SUMMARY_OUT_ENV_PATH
-            sudo -E -H -u github .github/scripts/tests/generate-summary.py \
-              --summary-out-path "$ARTIFACTS_DIR/summary/${i}/" \
-              --summary-out-env-path "$SUMMARY_OUT_ENV_PATH" \
-              --summary-url-prefix "$S3_WEBSITE_PREFIX/summary/${i}/" \
-              --build-preset "${platform_name}-${BUILD_PRESET}" \
-              "Tests" ya-test.html "${JUNIT_REPORT_XML}.${i}"
-
-            cat $SUMMARY_OUT_ENV_PATH | tee -a $GITHUB_STEP_SUMMARY
-            echo "::endgroup::"
-          fi
-        done
-
+        echo "Tests ended with exit code $END_EXIT_CODE"
+        exit $END_EXIT_CODE
 
     - name: Sync test results to S3
       if: always()
