Creating pool of CI vms to run on

diff --git a/.github/workflows/build_and_test_ya.yaml b/.github/workflows/build_and_test_ya.yaml
--- a/.github/workflows/build_and_test_ya.yaml
+++ b/.github/workflows/build_and_test_ya.yaml
@@ -19,16 +19,12 @@ on:
         description: "self-hosted or provisioned"
       runner_label:
         type: string
-        default: "linux"
+        default: "none"
         description: "runner label"
-      runner_instance_id:
+      runner_flavor:
         type: string
-        default: ""
-        description: "runner instance id"
-      runner_ipv4:
-        type: string
-        default: ""
-        description: "runner ipv4"
+        default: "none"
+        description: "runner flavor"
       run_build:
         type: boolean
         default: true
@@ -37,18 +33,6 @@ on:
         type: boolean
         default: true
         description: "run tests"
-      build_threads:
-        type: string
-        default: '60'
-        description: "Build threads count"
-      test_threads:
-        type: string
-        default: '64'
-        description: "Test threads count"
-      link_threads:
-        type: string
-        default: '32'
-        description: "link threads count"
       sleep_after_tests:
         type: string
         default: "0"
@@ -90,19 +74,46 @@ on:
         type: string
         default: "1"
         description: "Number of retries for tests"
-    outputs:
-      sleep_after_tests:
-        description: "sleep_after_tests"
-        value: ${{ jobs.build-and-test.outputs.sleep_after_tests }}
 
 jobs:
-  build-and-test:
-    name: Build and test ${{ inputs.build_preset }} [id=${{ inputs.runner_instance_id }} ip=${{ inputs.runner_ipv4 }}]
-    runs-on: [ self-hosted, "${{ inputs.runner_kind }}", "${{ inputs.runner_label }}" ]
+  calculate-runs-on:
+    name: Calculate runs-on
+    runs-on: [ self-hosted, "self-hosted", "runner_light" ]
     outputs:
-        sleep_after_tests: ${{ steps.failure.outputs.sleep_after_tests }}
-    timeout-minutes: 1440
+      runs-on: ${{ steps.set-runs-on.outputs.LABELS_LIST }}
     steps:
+      - name: set up runs on
+        id: set-runs-on
+        shell: bash --noprofile --norc -eo pipefail -x {0}
+        env:
+          RUNNER_LABEL: ${{ inputs.runner_label }}
+          RUNNER_FLAVOR: ${{ inputs.runner_flavor }}
+          RUNNER_KIND: ${{ inputs.runner_kind }}
+        run: |
+          LABELS_LIST='[]'
+          LABELS_LIST=$(echo "${LABELS_LIST}" | jq -c --arg gh_label "self-hosted" '. + [$gh_label]')
+          LABELS_LIST=$(echo "${LABELS_LIST}" | jq -c --arg gh_label "runner_${RUNNER_FLAVOR}" '. + [$gh_label]')
+          if [ "${RUNNER_LABEL}" != "none" ]; then
+            LABELS_LIST=$(echo "${LABELS_LIST}" | jq  -c --arg gh_label "${RUNNER_LABEL}" '. + [$gh_label]')
+          fi
+          echo "LABELS_LIST=${LABELS_LIST}" | tee -a "$GITHUB_OUTPUT"
+
+  build-and-test:
+    name: Build and test ${{ inputs.build_preset }}
+    runs-on: ${{ fromJson(needs.calculate-runs-on.outputs.runs-on) }}
+    timeout-minutes: 420
+    needs: calculate-runs-on
+    outputs:
+      # outcome failure and test_failed is null -> vm is broken
+      # failure and test_failed is 'no' -> tests failed, but vm is ok
+      # failure and test_failed is 'yes' -> tests failed, vm could be broken
+      test_failed: ${{ steps.test.outputs.test_failed || 'null' }}
+      test_run_outcome: ${{ steps.test.outcome }}
+    steps:
+    - name: Prepare workspace
+      shell: bash --noprofile --norc -eo pipefail -x {0}
+      run: |
+        chown -R root:root $GITHUB_WORKSPACE
     - name: Checkout PR
       uses: actions/checkout@v4
       if: github.event.pull_request.head.sha != ''
@@ -123,6 +134,44 @@ jobs:
       if: github.event.pull_request.head.sha == ''
       with:
         submodules: true
+        set-safe-directory: '*'
+
+    - name: set up nebius cli
+      id: cli
+      uses: ./.github/actions/nebius_cli
+      with:
+        sa_json: ${{ secrets.NEW_NEBIUS_SA_JSON_CREDENTIALS }}
+    - name: set up gh cli
+      id: gh
+      uses: ./.github/actions/gh_cli
+    - name: get runner info
+      id: get-runner
+      shell: bash --noprofile --norc -eo pipefail -x {0}
+      env:
+        RUNNER_NAME: ${{ runner.name }}
+      run: |
+        nebius compute instance get --id "${RUNNER_NAME}" --format json > instance.json
+        LABEL=$(jq -r '.metadata.labels."runner-label"' instance.json)
+        RUNNER_FLAVOR=$(jq -r '.metadata.labels."runner-flavor"' instance.json)
+        EXTERNAL_IPV4=$(jq -r '.status.network_interfaces[0].public_ip_address.address' instance.json | sed -e 's/\/32//g')
+        LOCAL_IPV4=$(jq -r '.status.network_interfaces[0].ip_address.address' instance.json | sed -e 's/\/32//g')
+        VM_PRESET=$(jq -r '.spec.resources.preset' instance.json)
+        {
+          echo "LABEL=${LABEL}"
+          echo "RUNNER_FLAVOR=${RUNNER_FLAVOR}"
+          echo "INSTANCE_ID=${INSTANCE_ID}"
+          echo "RUNNER_IPV4=${EXTERNAL_IPV4}"
+          echo "RUNNER_LOCAL_IPV4=${LOCAL_IPV4}"
+          echo "VM_PRESET=${VM_PRESET}"
+        } | tee -a "$GITHUB_OUTPUT"
+
+    - name: Calculate threads
+      id: calculate-threads
+      if: always()
+      uses: ./.github/actions/nebius_threads_calculator
+      with:
+        vm_preset: ${{ steps.get-runner.outputs.VM_PRESET }}
+        tests_size: ${{ inputs.test_size }}
 
     - name: Prepare s3cmd
       uses: ./.github/actions/s3cmd
@@ -136,22 +185,12 @@ jobs:
         build_preset: ${{ inputs.build_preset }}
         install: false
 
-    - name: Create background process that will adjust oom_score_adj for selection of processes
-      shell: bash
+    - name: install unattended-upgrades
+      shell: bash --noprofile --norc -eo pipefail -x {0}
       run: |
-        set -x
-        while true; do
-          echo "$(date) done sleeping" | tee -a /tmp/oom_score_adj.log
-          for pid in $(pgrep -f ydbd) $(pgrep -f qemu-system-x86_64); do
-            # check if process is already having oom_score_adj set to 500 if not then set it
-            if [ "$(cat /proc/$pid/oom_score_adj)" != "1000" ]; then
-              echo 1000 | sudo tee /proc/$pid/oom_score_adj
-              echo "set oom_score_adj=1000 for pid: $pid" | tee -a /tmp/oom_score_adj.log
-            fi
-          done
-          echo "$(date) sleeping for 30s" | tee -a /tmp/oom_score_adj.log
-          sleep 30
-        done &
+        [ -f /etc/apt/apt.conf.d/50unattended-upgrades ] && echo "unattended-upgrades already installed" && exit 0
+        sudo apt-get -o Dpkg::Lock::Timeout=600 update
+        sudo apt-get install -y unattended-upgrades
 
     - name: Build
       uses: ./.github/actions/build
@@ -163,13 +202,14 @@ jobs:
         bazel_remote_uri: ${{ vars.NEBIUS_BAZEL_REMOTE_CACHE_URL }}
         bazel_remote_username: ${{ secrets.REMOTE_CACHE_USERNAME }}
         bazel_remote_password: ${{ secrets.REMOTE_CACHE_PASSWORD }}
-        build_threads: ${{ inputs.build_threads }}
-        link_threads: ${{ inputs.link_threads }}
+        build_threads: ${{ steps.calculate-threads.outputs.build_threads }}
+        link_threads: ${{ steps.calculate-threads.outputs.link_threads }}
         clean_ya_dir: ${{ inputs.clean_ya_dir }}
         use_network_cache: ${{ inputs.use_network_cache }}
 
     - name: Run tests
       uses: ./.github/actions/test
+      id: test
       if: inputs.run_tests
       with:
         test_target: ${{ inputs.test_target }}
@@ -180,17 +220,160 @@ jobs:
         bazel_remote_uri: ${{ vars.NEBIUS_BAZEL_REMOTE_CACHE_URL }}
         bazel_remote_username: ${{ secrets.REMOTE_CACHE_USERNAME }}
         bazel_remote_password: ${{ secrets.REMOTE_CACHE_PASSWORD }}
-        link_threads: ${{ inputs.link_threads }}
-        test_threads: ${{ inputs.test_threads }}
+        link_threads: ${{ steps.calculate-threads.outputs.link_threads }}
+        test_threads: ${{ steps.calculate-threads.outputs.test_threads }}
         sync_to_s3: ${{ vars.SYNC_TO_S3 }}
         upload_ya_dir: ${{ inputs.upload_ya_dir }}
         clean_ya_dir: ${{ inputs.run_build && 'no' || inputs.clean_ya_dir }}
         use_network_cache: ${{ inputs.use_network_cache }}
         number_of_retries: ${{ inputs.number_of_retries }}
         truncate_enabled: ${{ inputs.truncate_enabled }}
-    - id: failure
-      name: set sleep_after_tests in case of failure
-      if: failure()
-      uses: ./.github/actions/sleep
-      with:
-        sleep_after_tests: ${{ inputs.sleep_after_tests != '0' && inputs.sleep_after_tests || '7200' }}
+    - id: sleep
+      name: Sleep after failed tests
+      if: ${{ inputs.sleep_after_tests != '0' && failure() }}
+      shell: bash --noprofile --norc -eo pipefail -x {0}
+      env:
+        SLEEP_AFTER_TESTS: ${{ inputs.sleep_after_tests || '7200' }}
+      run: |
+        sleep "$SLEEP_AFTER_TESTS"
+  debug:
+    name: Debug
+    runs-on: [self-hosted, "self-hosted", "runner_light"]
+    needs: 
+      - calculate-runs-on
+      - build-and-test
+    if: ${{ !cancelled() }}
+    steps:
+      - name: Debug info
+        shell: bash --noprofile --norc -eo pipefail -x {0}
+        run: |
+          echo "Test run outcome: ${{ needs.build-and-test.outputs.test_run_outcome }}"
+          echo "Test failed: ${{ needs.build-and-test.outputs.test_failed }}"
+          echo "Test run outcome is null: ${{ needs.build-and-test.outputs.test_run_outcome == null }}"
+          echo "Test failed is null: ${{ needs.build-and-test.outputs.test_failed == null }}"
+          echo "Test run outcome is failure: ${{ needs.build-and-test.outputs.test_run_outcome == 'failure' }}"
+          echo "Test failed is no: ${{ needs.build-and-test.outputs.test_failed == 'no' }}"
+          echo "Test failed is yes: ${{ needs.build-and-test.outputs.test_failed == 'yes' }}"
+          echo "Test run outcome is success: ${{ needs.build-and-test.outputs.test_run_outcome == 'success' }}"
+          echo "Test run outcome is skipped: ${{ needs.build-and-test.outputs.test_run_outcome == 'skipped' }}"
+          echo "Test run outcome is cancelled: ${{ needs.build-and-test.outputs.test_run_outcome == 'cancelled' }}"
+          echo "Test run outcome is empty: ${{ needs.build-and-test.outputs.test_run_outcome == '' }}"
+          echo "Test failed is empty: ${{ needs.build-and-test.outputs.test_failed == '' }}"
+          echo "Condition: ${{ needs.build-and-test.outputs.test_failed == null && needs.build-and-test.outputs.test_run_outcome == null }}"
+          echo "Condition: ${{ needs.build-and-test.outputs.test_failed == '' && needs.build-and-test.outputs.test_run_outcome == '' }}"
+          
+        env:
+          test_run_outcome: ${{ needs.build-and-test.outputs.test_run_outcome }}
+          test_failed: ${{ needs.build-and-test.outputs.test_failed }}
+          test_run_outcome_is_null: ${{ needs.build-and-test.outputs.test_run_outcome == null }}
+          test_failed_is_null: ${{ needs.build-and-test.outputs.test_failed == null }}
+          test_run_outcome_is_failure: ${{ needs.build-and-test.outputs.test_run_outcome == 'failure' }}
+          test_failed_is_no: ${{ needs.build-and-test.outputs.test_failed == 'no' }}
+          test_failed_is_yes: ${{ needs.build-and-test.outputs.test_failed == 'yes' }}
+          test_run_outcome_is_success: ${{ needs.build-and-test.outputs.test_run_outcome == 'success' }}
+          test_run_outcome_is_skipped: ${{ needs.build-and-test.outputs.test_run_outcome == 'skipped' }}
+          test_run_outcome_is_cancelled: ${{ needs.build-and-test.outputs.test_run_outcome == 'cancelled' }}
+          test_run_outcome_is_empty: ${{ needs.build-and-test.outputs.test_run_outcome == '' }}
+          test_failed_is_empty: ${{ needs.build-and-test.outputs.test_failed == '' }}
+    
+  test-retry:
+    name: Retry tests
+    runs-on: ${{ fromJson(needs.calculate-runs-on.outputs.runs-on) }}
+    needs: 
+      - calculate-runs-on
+      - build-and-test
+    # we can only rely on fact that test_failed can be null or 
+    if: ${{ failure() && (needs.build-and-test.outputs.test_failed == null && needs.build-and-test.outputs.test_run_outcome == null) }}
+    steps:
+      - name: Prepare workspace
+        shell: bash --noprofile --norc -eo pipefail -x {0}
+        run: |
+          chown -R root:root $GITHUB_WORKSPACE
+      - name: Checkout PR
+        uses: actions/checkout@v4
+        if: github.event.pull_request.head.sha != ''
+        with:
+          submodules: true
+          ref: ${{ github.event.pull_request.head.sha }}
+          fetch-depth: ${{ !contains(github.event.pull_request.labels.*.name, 'rebase') && 1 || 0 }}
+      - name: Rebase PR
+        if: ${{ github.event.pull_request.head.sha != '' && contains(github.event.pull_request.labels.*.name, 'rebase') }}
+        shell: bash
+        run: |
+          git config user.email "robot-nbs@nebius.com"
+          git config user.name "Robot NBS"
+          git fetch origin ${{ github.event.pull_request.base.ref }}
+          git rebase origin/${{ github.event.pull_request.base.ref }}
+      - name: Checkout
+        uses: actions/checkout@v4
+        if: github.event.pull_request.head.sha == ''
+        with:
+          submodules: true
+          set-safe-directory: '*'
+
+      - name: set up nebius cli
+        id: cli
+        uses: ./.github/actions/nebius_cli
+        with:
+          sa_json: ${{ secrets.NEW_NEBIUS_SA_JSON_CREDENTIALS }}
+      - name: set up gh cli
+        id: gh
+        uses: ./.github/actions/gh_cli
+      - name: get runner info
+        id: get-runner
+        shell: bash --noprofile --norc -eo pipefail -x {0}
+        env:
+          RUNNER_NAME: ${{ runner.name }}
+        run: |
+          nebius compute instance get --id "${RUNNER_NAME}" --format json > instance.json
+          LABEL=$(jq -r '.metadata.labels."runner-label"' instance.json)
+          RUNNER_FLAVOR=$(jq -r '.metadata.labels."runner-flavor"' instance.json)
+          EXTERNAL_IPV4=$(jq -r '.status.network_interfaces[0].public_ip_address.address' instance.json | sed -e 's/\/32//g')
+          LOCAL_IPV4=$(jq -r '.status.network_interfaces[0].ip_address.address' instance.json | sed -e 's/\/32//g')
+          VM_PRESET=$(jq -r '.spec.resources.preset' instance.json)
+          {
+            echo "LABEL=${LABEL}"
+            echo "RUNNER_FLAVOR=${RUNNER_FLAVOR}"
+            echo "INSTANCE_ID=${INSTANCE_ID}"
+            echo "RUNNER_IPV4=${EXTERNAL_IPV4}"
+            echo "RUNNER_LOCAL_IPV4=${LOCAL_IPV4}"
+            echo "VM_PRESET=${VM_PRESET}"
+          } | tee -a "$GITHUB_OUTPUT"
+
+      - name: Calculate threads
+        id: calculate-threads
+        if: always()
+        uses: ./.github/actions/nebius_threads_calculator
+        with:
+          vm_preset: ${{ steps.get-runner.outputs.VM_PRESET }}
+          tests_size: ${{ inputs.test_size }}
+
+      - name: Prepare s3cmd
+        uses: ./.github/actions/s3cmd
+        with:
+          s3_bucket: ${{ vars.AWS_BUCKET }}
+          s3_endpoint: ${{ vars.NEBIUS_AWS_ENDPOINT }}
+          s3_website_suffix: ${{ vars.NEBIUS_AWS_WEBSITE_SUFFIX }}
+          s3_key_id: ${{ secrets.NEBIUS_AWS_ACCESS_KEY_ID }}
+          s3_key_secret: ${{ secrets.NEBIUS_AWS_SECRET_ACCESS_KEY }}
+          folder_prefix: nebius-
+          build_preset: ${{ inputs.build_preset }}
+          install: false
+      - name: Run tests
+        uses: ./.github/actions/test
+        id: test
+        with:
+          test_target: ${{ inputs.test_target }}
+          build_preset: ${{ inputs.build_preset }}
+          test_size: ${{ inputs.test_size }}
+          test_type: ${{ inputs.test_type }}
+          bazel_remote_uri: ${{ vars.NEBIUS_BAZEL_REMOTE_CACHE_URL }}
+          bazel_remote_username: ${{ secrets.REMOTE_CACHE_USERNAME }}
+          bazel_remote_password: ${{ secrets.REMOTE_CACHE_PASSWORD }}
+          link_threads: ${{ steps.calculate-threads.outputs.link_threads }}
+          test_threads: ${{ steps.calculate-threads.outputs.test_threads }}
+          sync_to_s3: ${{ vars.SYNC_TO_S3 }}
+          upload_ya_dir: ${{ inputs.upload_ya_dir }}
+          clean_ya_dir: ${{ inputs.clean_ya_dir }}
+          use_network_cache: ${{ inputs.use_network_cache }}
+          number_of_retries: ${{ inputs.number_of_retries }}
